#!/usr/bin/env python3
"""Media pipeline: curated screenshots -> public/media WebP masters + blur placeholders
+ 3D screen textures + generated TS manifest. Originals never enter public/."""
from PIL import Image, ImageOps
import os, io, base64, json

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SS = "/home/claude/src-material/app_ss/app_ss"
ED = "/home/claude/edited"
PUB = os.path.join(ROOT, "public", "media")

CURATION = {
    "naqiverse": [
        ("01-home", f"{SS}/naqiverse/Home.jpeg"),
        ("02-profile", f"{SS}/naqiverse/Profile.jpeg"),
        ("03-leaderboard", f"{ED}/naqiverse/03-leaderboard.jpeg"),
        ("04-friends", f"{ED}/naqiverse/04-friends.jpeg"),
        ("05-stats", f"{ED}/naqiverse/05-stats.jpeg"),
        ("06-leaderboard-row", f"{ED}/naqiverse/06-leaderboard-row.jpeg"),
        ("07-badges", f"{SS}/naqiverse/Achievements.jpeg"),
        ("08-theme-shop", f"{SS}/naqiverse/Theme Shop.jpeg"),
        ("09-settings", f"{SS}/naqiverse/Settings.jpeg"),
        ("10-about", f"{SS}/naqiverse/About.jpeg"),
    ],
    "aimara": [
        ("01-login", f"{ED}/AImara/01-login.png"),
        ("02-channels-empty", f"{SS}/AImara/Screenshot 2026-08-04 114356.png"),
        ("03-channels", f"{ED}/AImara/03-channels.png"),
        ("04-new-channel", f"{SS}/AImara/Screenshot 2026-08-04 114435.png"),
        ("05-chat-privacy", f"{SS}/AImara/Screenshot 2026-08-04 114423.png"),
        ("06-dashboard", f"{ED}/AImara/06-dashboard.png"),
        ("07-starred", f"{ED}/AImara/07-starred.png"),
    ],
    "grocs": [
        ("01-welcome", f"{SS}/grocs/Screenshot_1785813302.png"),
        ("02-starter-index", f"{SS}/grocs/Screenshot_1785813305.png"),
        ("03-themes", f"{SS}/grocs/Screenshot_1785813311.png"),
        ("04-privacy", f"{SS}/grocs/Screenshot_1785813313.png"),
        ("05-on-device-ai", f"{SS}/grocs/Screenshot_1785813315.png"),
        ("06-home", f"{SS}/grocs/Screenshot_1785813318.png"),
        ("07-add", f"{SS}/grocs/Screenshot_1785813323.png"),
        ("08-recipes", f"{SS}/grocs/Screenshot_1785813321.png"),
        ("09-pantry", f"{SS}/grocs/Screenshot_1785813325.png"),
        ("10-shopping", f"{SS}/grocs/Screenshot_1785813327.png"),
        ("11-you", f"{SS}/grocs/Screenshot_1785813336.png"),
    ],
    "dentxpert": [
        ("01-model-selection", f"{SS}/dentxpert/Screenshot_20240609_204014.jpg"),
    ],
}

TEXTURES = [
    ("naqiverse", f"{SS}/naqiverse/Home.jpeg"),
    ("aimara", f"{SS}/AImara/Screenshot 2026-08-04 114423.png"),
    ("grocs", f"{SS}/grocs/Screenshot_1785813321.png"),
]

MAX_W = 1080  # cap master width; originals above this are downscaled

def open_clean(path):
    im = Image.open(path)
    im = ImageOps.exif_transpose(im).convert("RGB")  # re-encode drops metadata
    return im

manifest = {}
for project, items in CURATION.items():
    outdir = os.path.join(PUB, project)
    os.makedirs(outdir, exist_ok=True)
    for slug, src in items:
        im = open_clean(src)
        if im.width > MAX_W:
            im = im.resize((MAX_W, round(im.height * MAX_W / im.width)), Image.LANCZOS)
        out = os.path.join(outdir, f"{slug}.webp")
        im.save(out, "WEBP", quality=88, method=6)
        tiny = im.resize((20, max(1, round(im.height * 20 / im.width))), Image.LANCZOS)
        buf = io.BytesIO(); tiny.save(buf, "WEBP", quality=40)
        blur = "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode()
        manifest[f"{project}/{slug}"] = {
            "src": f"/media/{project}/{slug}.webp",
            "width": im.width, "height": im.height, "blurDataURL": blur,
        }
        print(f"{project}/{slug}: {im.width}x{im.height} {os.path.getsize(out)//1024}kb")

os.makedirs(os.path.join(PUB, "textures"), exist_ok=True)
for slug, src in TEXTURES:
    im = open_clean(src)
    im = im.resize((420, round(im.height * 420 / im.width)), Image.LANCZOS)
    out = os.path.join(PUB, "textures", f"{slug}.webp")
    im.save(out, "WEBP", quality=70, method=6)
    print(f"texture {slug}: {os.path.getsize(out)//1024}kb")

gen = os.path.join(ROOT, "src", "content", "media.gen.ts")
os.makedirs(os.path.dirname(gen), exist_ok=True)
with open(gen, "w") as f:
    f.write("// GENERATED by tools/media/build-media.py — do not edit by hand.\n")
    f.write("export interface MediaAsset { src: string; width: number; height: number; blurDataURL: string }\n\n")
    f.write("export const MEDIA = ")
    f.write(json.dumps(manifest, indent=2))
    f.write(" as const satisfies Record<string, MediaAsset>;\n\n")
    f.write("export type MediaId = keyof typeof MEDIA;\n")
print("manifest ->", gen, f"({len(manifest)} assets)")
